/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import static controller.ControladorPrincipal.*;

/**
 *
 * @author Lucas
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botonOrder = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        botonMenu = new javax.swing.JMenu();
        menuClientes = new javax.swing.JMenu();
        itemAgregarCl = new javax.swing.JMenuItem();
        itemModificarCl = new javax.swing.JMenuItem();
        menuPedidos = new javax.swing.JMenu();
        itemAgregarPed = new javax.swing.JMenuItem();
        itemModificarPed = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Bienvenido a ClassicModel!");

        botonOrder.setBackground(new java.awt.Color(255, 255, 255));
        botonOrder.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        botonOrder.setText("Clientes/Pedidos");
        botonOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOrderActionPerformed(evt);
            }
        });

        botonMenu.setText("Opciones");

        menuClientes.setText("Clientes");

        itemAgregarCl.setText("Agregar Cliente");
        itemAgregarCl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarClActionPerformed(evt);
            }
        });
        menuClientes.add(itemAgregarCl);

        itemModificarCl.setText("Modificar Cliente");
        menuClientes.add(itemModificarCl);

        botonMenu.add(menuClientes);

        menuPedidos.setText("Pedidos");

        itemAgregarPed.setText("Agregar Pedido");
        menuPedidos.add(itemAgregarPed);

        itemModificarPed.setText("Modificar Pedido");
        menuPedidos.add(itemModificarPed);

        botonMenu.add(menuPedidos);

        jMenuBar2.add(botonMenu);

        jMenu5.setText("Ayuda");
        jMenuBar2.add(jMenu5);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(botonOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(botonOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOrderActionPerformed
        VentanaOrdenes();
    }//GEN-LAST:event_botonOrderActionPerformed

    private void itemAgregarClActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarClActionPerformed
        VentanaAgregarCliente();
    }//GEN-LAST:event_itemAgregarClActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu botonMenu;
    private javax.swing.JButton botonOrder;
    private javax.swing.JMenuItem itemAgregarCl;
    private javax.swing.JMenuItem itemAgregarPed;
    private javax.swing.JMenuItem itemModificarCl;
    private javax.swing.JMenuItem itemModificarPed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu menuClientes;
    private javax.swing.JMenu menuPedidos;
    // End of variables declaration//GEN-END:variables
}
